export enum RouterEnum {
  Auth = "/auth",
  PlannedTrips = "/trips/planned",
  DraftTrips = "/trips/drafts",
  Trip = "/trip/:tripId",
  NewTripByUser = "/new-trip-by-user",
  NewTripByAI = "/new-trip-by-ai",
  NewTripModeChoice = "/new-trip-mode-choice",
  Registration = "/registration",
  Login = "/login",
  Verification = "/verify-email",
  TripMates = "/trip-mates",
  Chats = "/chats",
  NotFound = "/not-found",
}
